### ISSUE TITLE
Unable to specify custom paper sizes

### ISSUE THREAD

**Issue by me-and** [frsche/cardimpose#1]
Hello!

I think I've found a bug that means it's impossible to specify custom paper sizes, whether using the `cardimpose` executable or the Python library `CardImpose.set_page_size` method.

Currently, specifying a page size like `A4` works as expected, and it looks like the code at [`CardImpose.set_page_size`](https://github.com/frsche/cardimpose/blob/23e0d3d891b26d262b03c269e90a8a7291accfbd/cardimpose/cardimpose.py#L108-L115) is supposed to handle setting the page size as a tuple as well (e.g. `(595, 842)` for A4). However, if the input is a string, the code calls [`fitz.paper_size`](https://pymupdf.readthedocs.io/en/latest/functions.html#paper_size), which can only handle standard paper sizes, and if the input is not a string, calls through to [`parse_tuple`](https://github.com/frsche/cardimpose/blob/23e0d3d891b26d262b03c269e90a8a7291accfbd/cardimpose/parse.py#L23-L32), which immediately asserts the input _is_ a string and so always fails.

I'm not quite sure what the correct fix is, as I'm not sure what the intended interface is: should `set_page_size` accept a tuple of strings (which seems to be what's expected in `CardImpose.set_page_size`) or a string like `"2cm x 2cm"` (which seems to be what's expected by `parse_tuple`). Or both, or something else entirely...?

**Comment by frsche** [comment]
Hello,
yes, you are right. I would say `set_page_size` should receive either a string (such as `A4`) or a tuple of strings (containing numbers with unit, such as `("2cm", "2cm")`). Splitting on the `x` should be done when parsing command line arguments in my opinion. Or what do you think?
